services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    volumes:
      - ./mlflow_db:/app/db
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_S3_REGION:-us-east-1}
      - MLFLOW_BACKEND_STORE_URI=sqlite:////app/db/mlflow.db
      - MLFLOW_ARTIFACT_ROOT=s3://${AWS_S3_BUCKET_NAME:-flights-forecasting}/mlflow
      - MLFLOW_HOST=0.0.0.0
      - MLFLOW_PORT=5000
    restart: unless-stopped
